name: Build & Push to Public ECR

on:
  push:
    branches: [main]

env:
  REGISTRY: public.ecr.aws
  REPO_PREFIX: s9l9d5k8
  IMAGE_NAME: sanbei/postgrest
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Amazon Public ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1   # 公有 ECR 只在美国东区有入口,这里必须写 us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./deploy
          file: ./deploy/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_PREFIX }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.REPO_PREFIX }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}