name: lint
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: run linter
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v5

    - uses: astral-sh/ruff-action@v3
      with:
        version-file: "pyproject.toml"

    - run: ruff check