name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: generate sql files
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v5

    - name: set up python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - uses: astral-sh/setup-uv@v7
    
    - name: generate sql
      run: |
        uv run python *-fake.py

    - name: upload release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: sql
        files: |
          *-fake.sql
        make_latest: true